services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"        # ← phải có dòng này
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - //var/run/docker.sock:/var/run/docker.sock
    user: root
    restart: unless-stopped

volumes:
  jenkins_home: